// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EquipItem.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_EquipItem_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_EquipItem_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_EquipItem_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_EquipItem_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_EquipItem_2eproto;
namespace Protocol {
class EquipItem;
struct EquipItemDefaultTypeInternal;
extern EquipItemDefaultTypeInternal _EquipItem_default_instance_;
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> ::Protocol::EquipItem* Arena::CreateMaybeMessage<::Protocol::EquipItem>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

// ===================================================================

class EquipItem final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.EquipItem) */ {
 public:
  inline EquipItem() : EquipItem(nullptr) {}
  ~EquipItem() override;
  explicit PROTOBUF_CONSTEXPR EquipItem(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  EquipItem(const EquipItem& from);
  EquipItem(EquipItem&& from) noexcept
    : EquipItem() {
    *this = ::std::move(from);
  }

  inline EquipItem& operator=(const EquipItem& from) {
    CopyFrom(from);
    return *this;
  }
  inline EquipItem& operator=(EquipItem&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const EquipItem& default_instance() {
    return *internal_default_instance();
  }
  static inline const EquipItem* internal_default_instance() {
    return reinterpret_cast<const EquipItem*>(
               &_EquipItem_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(EquipItem& a, EquipItem& b) {
    a.Swap(&b);
  }
  inline void Swap(EquipItem* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EquipItem* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  EquipItem* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<EquipItem>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const EquipItem& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const EquipItem& from) {
    EquipItem::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(EquipItem* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.EquipItem";
  }
  protected:
  explicit EquipItem(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSlotIndexFieldNumber = 1,
    kEquipItemIndexFieldNumber = 2,
    kStarFieldNumber = 3,
  };
  // uint64 SlotIndex = 1;
  void clear_slotindex();
  uint64_t slotindex() const;
  void set_slotindex(uint64_t value);
  private:
  uint64_t _internal_slotindex() const;
  void _internal_set_slotindex(uint64_t value);
  public:

  // uint64 EquipItemIndex = 2;
  void clear_equipitemindex();
  uint64_t equipitemindex() const;
  void set_equipitemindex(uint64_t value);
  private:
  uint64_t _internal_equipitemindex() const;
  void _internal_set_equipitemindex(uint64_t value);
  public:

  // uint64 Star = 3;
  void clear_star();
  uint64_t star() const;
  void set_star(uint64_t value);
  private:
  uint64_t _internal_star() const;
  void _internal_set_star(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.EquipItem)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t slotindex_;
    uint64_t equipitemindex_;
    uint64_t star_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_EquipItem_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// EquipItem

// uint64 SlotIndex = 1;
inline void EquipItem::clear_slotindex() {
  _impl_.slotindex_ = uint64_t{0u};
}
inline uint64_t EquipItem::_internal_slotindex() const {
  return _impl_.slotindex_;
}
inline uint64_t EquipItem::slotindex() const {
  // @@protoc_insertion_point(field_get:Protocol.EquipItem.SlotIndex)
  return _internal_slotindex();
}
inline void EquipItem::_internal_set_slotindex(uint64_t value) {
  
  _impl_.slotindex_ = value;
}
inline void EquipItem::set_slotindex(uint64_t value) {
  _internal_set_slotindex(value);
  // @@protoc_insertion_point(field_set:Protocol.EquipItem.SlotIndex)
}

// uint64 EquipItemIndex = 2;
inline void EquipItem::clear_equipitemindex() {
  _impl_.equipitemindex_ = uint64_t{0u};
}
inline uint64_t EquipItem::_internal_equipitemindex() const {
  return _impl_.equipitemindex_;
}
inline uint64_t EquipItem::equipitemindex() const {
  // @@protoc_insertion_point(field_get:Protocol.EquipItem.EquipItemIndex)
  return _internal_equipitemindex();
}
inline void EquipItem::_internal_set_equipitemindex(uint64_t value) {
  
  _impl_.equipitemindex_ = value;
}
inline void EquipItem::set_equipitemindex(uint64_t value) {
  _internal_set_equipitemindex(value);
  // @@protoc_insertion_point(field_set:Protocol.EquipItem.EquipItemIndex)
}

// uint64 Star = 3;
inline void EquipItem::clear_star() {
  _impl_.star_ = uint64_t{0u};
}
inline uint64_t EquipItem::_internal_star() const {
  return _impl_.star_;
}
inline uint64_t EquipItem::star() const {
  // @@protoc_insertion_point(field_get:Protocol.EquipItem.Star)
  return _internal_star();
}
inline void EquipItem::_internal_set_star(uint64_t value) {
  
  _impl_.star_ = value;
}
inline void EquipItem::set_star(uint64_t value) {
  _internal_set_star(value);
  // @@protoc_insertion_point(field_set:Protocol.EquipItem.Star)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_EquipItem_2eproto
